<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ListIndikatorKeluaranSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //Indikator Keluaran
        DB::table('list_indikator_keluarans')->delete();

        DB::table('list_indikator_keluarans')->insert(array (
            0 => array (
                'id' => 1, 
                'id_keluaran' => 1, 
                'indikator_keluaran' => 'Jumlah dokumen koordinasi dan sinkronisasi pengumpulan, pengolahan, analisis, dan diseminasi data statistik sektoral',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 1,
                'id_program' => 1,
                'id_kegiatan' => 35,
                'id_subkegiatan' => 1,
                'id_instansi' => 5
            ),
            1 => array (
                'id' => 2, 
                'id_keluaran' => 2, 
                'indikator_keluaran' => 'Jumlah Dokumen Koordinasi Pelaksanaan Penataan Ruang',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 1,
                'id_program' => 4,
                'id_kegiatan' => 5,
                'id_subkegiatan' => 9,
                'id_instansi' => 10
            ),
            2 => array (
                'id' => 3, 
                'id_keluaran' => 3, 
                'indikator_keluaran' => 'Jumlah kegiatan pengawasan penggunaan sarana pertanian',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 1,
                'id_program' => 6,
                'id_kegiatan' => 28,
                'id_subkegiatan' => 11,
                'id_instansi' => 10
            ),
            3 => array (
                'id' => 4, 
                'id_keluaran' => 4, 
                'indikator_keluaran' => 'Jumlah kegiatan peningkatan kapasitas ',
                'target' => 360,
                'satuan' => 'peserta',
                'id_komponen' => 1,
                'id_program' => 2,
                'id_kegiatan' => 5,
                'id_subkegiatan' => 7,
                'id_instansi' => 10
            ),
            4 => array (
                'id' => 5, 
                'id_keluaran' => 5, 
                'indikator_keluaran' => 'Jumlah orang yang dibina dalam pemanfaatan data dan informasi',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 1,
                'id_program' => 1,
                'id_kegiatan' => 1,
                'id_subkegiatan' => 2,
                'id_instansi' => 1
            ),
            5 => array (
                'id' => 6, 
                'id_keluaran' => 6, 
                'indikator_keluaran' => 'Jumlah paket pembangunan, rehabilitasi, dan  pemeliharaan jalan usaha tani',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 1,
                'id_program' => 6,
                'id_kegiatan' => 12,
                'id_subkegiatan' => 10,
                'id_instansi' => 10
            ),
            6 => array (
                'id' => 7, 
                'id_keluaran' => 7, 
                'indikator_keluaran' => 'Jumlah pekebun yang dilibatkan ',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 1,
                'id_program' => 3,
                'id_kegiatan' => 7,
                'id_subkegiatan' => 8,
                'id_instansi' => 10
            ),
            7 => array (
                'id' => 8, 
                'id_keluaran' => 8, 
                'indikator_keluaran' => 'Jumlah pelaku usaha yang dibina',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 1,
                'id_program' => 7,
                'id_kegiatan' => 26,
                'id_subkegiatan' => 45,
                'id_instansi' => 10
            ),
            8 => array (
                'id' => 9, 
                'id_keluaran' => 9, 
                'indikator_keluaran' => 'Jumlah Perusahaan yang Melaksanakan Pengesahan Peraturan Perusahaan yang Terkait dengan Hubungan Industrial dan Terdaftar di WLKP Online',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 1,
                'id_program' => 7,
                'id_kegiatan' => 31,
                'id_subkegiatan' => 12,
                'id_instansi' => 4
            ),
            9 => array (
                'id' => 10, 
                'id_keluaran' => 10, 
                'indikator_keluaran' => 'Tersedianya basis data spasial dan non spasial kelapa sawit',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 1,
                'id_program' => 2,
                'id_kegiatan' => 6,
                'id_subkegiatan' => 5,
                'id_instansi' => 10
            ),
            10 => array (
                'id' => 11, 
                'id_keluaran' => 11, 
                'indikator_keluaran' => 'Tersedianya data statistik perkebunan sawit rakyat dan perusahaan Kabupaten Labuanbatu Utara',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 1,
                'id_program' => 1,
                'id_kegiatan' => 35,
                'id_subkegiatan' => 1,
                'id_instansi' => 5
            ),
            11 => array (
                'id' => 12, 
                'id_keluaran' => 12, 
                'indikator_keluaran' => 'Tersedianya Informasi Geospasial Tematik tutupan lahan kelapa sawit',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 1,
                'id_program' => 2,
                'id_kegiatan' => 6,
                'id_subkegiatan' => 6,
                'id_instansi' => 10
            ),
            12 => array (
                'id' => 13, 
                'id_keluaran' => 13, 
                'indikator_keluaran' => 'Tersusunnya buku profil kebun sawit rayat dan petani kelapa sawit',
                'target' => 1,
                'satuan' => 'buku profil',
                'id_komponen' => 1,
                'id_program' => 1,
                'id_kegiatan' => 14,
                'id_subkegiatan' => 4,
                'id_instansi' => 3
            ),
            13 => array (
                'id' => 14, 
                'id_keluaran' => 14, 
                'indikator_keluaran' => 'Tersusunnya buku profil pembangunan daerah kabupaten',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 1,
                'id_program' => 1,
                'id_kegiatan' => 13,
                'id_subkegiatan' => 3,
                'id_instansi' => 1
            ),
            14 => array (
                'id' => 15, 
                'id_keluaran' => 15, 
                'indikator_keluaran' => 'Jumlah Badan Usaha Milik Petani yang terbentuk',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 2,
                'id_program' => 11,
                'id_kegiatan' => 7,
                'id_subkegiatan' => 21,
                'id_instansi' => 10
            ),
            15 => array (
                'id' => 16, 
                'id_keluaran' => 16, 
                'indikator_keluaran' => 'Jumlah BPP penerima manfaat sarana dan prasarana penyuluhan pertanian',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 2,
                'id_program' => 9,
                'id_kegiatan' => 7,
                'id_subkegiatan' => 15,
                'id_instansi' => 10
            ),
            16 => array (
                'id' => 17, 
                'id_keluaran' => 17, 
                'indikator_keluaran' => 'Jumlah kegiatan pengawasan ',
                'target' => 6,
                'satuan' => 'kegiatan pengawasan',
                'id_komponen' => 2,
                'id_program' => 8,
                'id_kegiatan' => 28,
                'id_subkegiatan' => 14,
                'id_instansi' => 10
            ),
            17 => array (
                'id' => 18, 
                'id_keluaran' => 18, 
                'indikator_keluaran' => 'Jumlah kegiatan penyuluhan penggunaan benih bersertifikat',
                'target' => 11,
                'satuan' => 'kegiatan penyuluhan',
                'id_komponen' => 2,
                'id_program' => 8,
                'id_kegiatan' => 7,
                'id_subkegiatan' => 13,
                'id_instansi' => 10
            ),
            18 => array (
                'id' => 19, 
                'id_keluaran' => 19, 
                'indikator_keluaran' => 'Jumlah kemitraan yang terbentuk untuk realisasi KUR PSR',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 2,
                'id_program' => 10,
                'id_kegiatan' => 30,
                'id_subkegiatan' => 18,
                'id_instansi' => 14
            ),
            19 => array (
                'id' => 20, 
                'id_keluaran' => 20, 
                'indikator_keluaran' => 'Jumlah pekebun yang terlibat dalam kegiatan peningkatan kapasitas',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 2,
                'id_program' => 10,
                'id_kegiatan' => 7,
                'id_subkegiatan' => 19,
                'id_instansi' => 10
            ),
            20 => array (
                'id' => 21, 
                'id_keluaran' => 21, 
                'indikator_keluaran' => 'Jumlah pelatihan yang dilakukan untuk koperasi petani sawit',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 2,
                'id_program' => 11,
                'id_kegiatan' => 24,
                'id_subkegiatan' => 22,
                'id_instansi' => 9
            ),
            21 => array (
                'id' => 22, 
                'id_keluaran' => 22, 
                'indikator_keluaran' => 'Jumlah pertemuan pembinaan bagi kelembagaan penyuluh pertanian',
                'target' => 36,
                'satuan' => 'pertemuan',
                'id_komponen' => 2,
                'id_program' => 9,
                'id_kegiatan' => 7,
                'id_subkegiatan' => 16,
                'id_instansi' => 10
            ),
            22 => array (
                'id' => 23, 
                'id_keluaran' => 23, 
                'indikator_keluaran' => 'Jumlah peserta kegiatan pengembangan kapasitas kelembagaan petani',
                'target' => 360,
                'satuan' => 'peserta',
                'id_komponen' => 2,
                'id_program' => 11,
                'id_kegiatan' => 7,
                'id_subkegiatan' => 20,
                'id_instansi' => 10
            ),
            23 => array (
                'id' => 24, 
                'id_keluaran' => 24, 
                'indikator_keluaran' => 'Jumlah petani sawit yang terlibat dalam pelatihan perkoperasian',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 2,
                'id_program' => 11,
                'id_kegiatan' => 24,
                'id_subkegiatan' => 22,
                'id_instansi' => 9
            ),
            24 => array (
                'id' => 25, 
                'id_keluaran' => 25, 
                'indikator_keluaran' => 'Jumlah Unit Usaha Koperasi Petani Sawit yang Telah Dilakukan Penilaian Kesehatan',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 2,
                'id_program' => 11,
                'id_kegiatan' => 32,
                'id_subkegiatan' => 23,
                'id_instansi' => 9
            ),
            25 => array (
                'id' => 26, 
                'id_keluaran' => 26, 
                'indikator_keluaran' => 'Tersedianya rumusan rekomendasi kebijakan penelitian dan pengembangan badan usaha milik daerah untuk pabrik kelapa sawit/palm oil mill',
                'target' => 1,
                'satuan' => 'laporan',
                'id_komponen' => 2,
                'id_program' => 9,
                'id_kegiatan' => 4,
                'id_subkegiatan' => 17,
                'id_instansi' => 1
            ),
            26 => array (
                'id' => 27, 
                'id_keluaran' => 27, 
                'indikator_keluaran' => 'Jumlah aksi mitigasi yang dilaporkan',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 16,
                'id_kegiatan' => 20,
                'id_subkegiatan' => 39,
                'id_instansi' => 6
            ),
            27 => array (
                'id' => 28, 
                'id_keluaran' => 28, 
                'indikator_keluaran' => 'Jumlah Desa/Kelurahan yang Terbentuk dan Terbina Relawan Pemadam Kebakaran pada Lingkup Sistem Ketahanan Kebakaran Lingkungan (SKKL) Setiap Tahunnya',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 14,
                'id_kegiatan' => 15,
                'id_subkegiatan' => 35,
                'id_instansi' => 8
            ),
            28 => array (
                'id' => 29, 
                'id_keluaran' => 29, 
                'indikator_keluaran' => 'Jumlah kasus yang ditangani',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 13,
                'id_kegiatan' => 25,
                'id_subkegiatan' => 27,
                'id_instansi' => 6
            ),
            29 => array (
                'id' => 30, 
                'id_keluaran' => 30, 
                'indikator_keluaran' => 'Jumlah kegiatan pemantauan yang dilakukan ',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 13,
                'id_kegiatan' => 11,
                'id_subkegiatan' => 26,
                'id_instansi' => 6
            ),
            30 => array (
                'id' => 31, 
                'id_keluaran' => 31, 
                'indikator_keluaran' => 'Jumlah kegiatan penyuluhan dan kampanye lingkungan',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 13,
                'id_kegiatan' => 33,
                'id_subkegiatan' => 24,
                'id_instansi' => 6
            ),
            31 => array (
                'id' => 32, 
                'id_keluaran' => 32, 
                'indikator_keluaran' => 'Jumlah kegiatan promosi produk hasil pengelolaan limbah kelapa sawit yang dilakukan',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 18,
                'id_kegiatan' => 37,
                'id_subkegiatan' => 44,
                'id_instansi' => 9
            ),
            32 => array (
                'id' => 33, 
                'id_keluaran' => 33, 
                'indikator_keluaran' => 'Jumlah kegiatan sosialisasi yang dilakukan',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 13,
                'id_kegiatan' => 38,
                'id_subkegiatan' => 28,
                'id_instansi' => 6
            ),
            33 => array (
                'id' => 34, 
                'id_keluaran' => 34, 
                'indikator_keluaran' => 'Jumlah Laporan Hasil Pelaksanaan Monitoring, Evaluasi dan Pelaporan Pemenuhan Target dan Standar Pelayanan Pengelolaan Sampah Kabupaten/Kota',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 18,
                'id_kegiatan' => 17,
                'id_subkegiatan' => 41,
                'id_instansi' => 9
            ),
            34 => array (
                'id' => 35, 
                'id_keluaran' => 35, 
                'indikator_keluaran' => 'Jumlah orang yang memperoleh Sosialisasi KIE Rawan Bencana',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 14,
                'id_kegiatan' => 9,
                'id_subkegiatan' => 32,
                'id_instansi' => 2
            ),
            35 => array (
                'id' => 36, 
                'id_keluaran' => 36, 
                'indikator_keluaran' => 'Jumlah personil TRC yang dikembangkan kapasitas teknis dan manajerialnya',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 14,
                'id_kegiatan' => 10,
                'id_subkegiatan' => 31,
                'id_instansi' => 2
            ),
            36 => array (
                'id' => 37, 
                'id_keluaran' => 37, 
                'indikator_keluaran' => 'Jumlah perusahaan yang melaporkan hasil pemantauan',
                'target' => 100,    
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 14,
                'id_kegiatan' => 18,
                'id_subkegiatan' => 36,
                'id_instansi' => 6
            ),
            37 => array (
                'id' => 38, 
                'id_keluaran' => 38, 
                'indikator_keluaran' => 'Jumlah Sarana dan Prasarana Untuk Pencegahan dan Penanggulangan Kebakaran dan Alat Pelindung Diri yang Sah dan Legal Sesuai Standar Teknis Terkait',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 14,
                'id_kegiatan' => 21,
                'id_subkegiatan' => 29,
                'id_instansi' => 8
            ),
            38 => array (
                'id' => 39, 
                'id_keluaran' => 39, 
                'indikator_keluaran' => 'Jumlah unit bantuan yang disalurkan',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 18,
                'id_kegiatan' => 2,
                'id_subkegiatan' => 43,
                'id_instansi' => 9
            ),
            39 => array (
                'id' => 40, 
                'id_keluaran' => 40, 
                'indikator_keluaran' => 'Jumlah Unit Usaha pengelolaan limbah kelapa sawit yang Telah Menerima Pembinaan dan Pendampingan Terhadap Usaha Mikro',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 18,
                'id_kegiatan' => 16,
                'id_subkegiatan' => 42,
                'id_instansi' => 9
            ),
            40 => array (
                'id' => 41, 
                'id_keluaran' => 41, 
                'indikator_keluaran' => 'Jumlah warga negara dan aparatur yang mengikuti pelatihan pencegahan dan mitigasi bencana',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 14,
                'id_kegiatan' => 10,
                'id_subkegiatan' => 33,
                'id_instansi' => 2
            ),
            41 => array (
                'id' => 42, 
                'id_keluaran' => 42, 
                'indikator_keluaran' => 'Luas agroforestri sawit ',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 13,
                'id_kegiatan' => 29,
                'id_subkegiatan' => 25,
                'id_instansi' => 6
            ),
            42 => array (
                'id' => 43, 
                'id_keluaran' => 43, 
                'indikator_keluaran' => 'Luas agroforestri sawit',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 17,
                'id_kegiatan' => 18,
                'id_subkegiatan' => 40,
                'id_instansi' => 6
            ),
            43 => array (
                'id' => 44, 
                'id_keluaran' => 44, 
                'indikator_keluaran' => 'Terdapat data hasil inventarisasi emisi GRK secara berkala',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 15,
                'id_kegiatan' => 20,
                'id_subkegiatan' => 37,
                'id_instansi' => 6
            ),
            44 => array (
                'id' => 45, 
                'id_keluaran' => 45, 
                'indikator_keluaran' => 'Terdapat profil emisi GRK Kabupaten Labuanbatu Utara',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 15,
                'id_kegiatan' => 20,
                'id_subkegiatan' => 38,
                'id_instansi' => 6
            ),
            45 => array (
                'id' => 46, 
                'id_keluaran' => 46, 
                'indikator_keluaran' => 'Tersedianya RPB kebakaran hutan dan lahan',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 14,
                'id_kegiatan' => 10,
                'id_subkegiatan' => 30,
                'id_instansi' => 2
            ),
            46 => array (
                'id' => 47, 
                'id_keluaran' => 47, 
                'indikator_keluaran' => 'Tersusunnya kajian risiko bencana kebakaran',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 3,
                'id_program' => 14,
                'id_kegiatan' => 9,
                'id_subkegiatan' => 34,
                'id_instansi' => 2
            ),
            47 => array (
                'id' => 48, 
                'id_keluaran' => 48, 
                'indikator_keluaran' => 'Jumlah dokumen pengendalian dan pemanfaatan ruang yang sesuai',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 4,
                'id_program' => 21,
                'id_kegiatan' => 5,
                'id_subkegiatan' => 46,
                'id_instansi' => 7
            ),
            48 => array (
                'id' => 49, 
                'id_keluaran' => 49, 
                'indikator_keluaran' => 'Jumlah kegiatan pendampingan yang dilakukan',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 4,
                'id_program' => 23,
                'id_kegiatan' => 22,
                'id_subkegiatan' => 51,
                'id_instansi' => 13
            ),
            49 => array (
                'id' => 50, 
                'id_keluaran' => 50, 
                'indikator_keluaran' => 'Jumlah kelompok yang difasilitasi dalam pengajuan skema PS',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 4,
                'id_program' => 22,
                'id_kegiatan' => 27,
                'id_subkegiatan' => 48,
                'id_instansi' => 1
            ),
            50 => array (
                'id' => 51, 
                'id_keluaran' => 51, 
                'indikator_keluaran' => 'Jumlah pekebun yang difasilitasi',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 4,
                'id_program' => 21,
                'id_kegiatan' => 3,
                'id_subkegiatan' => 47,
                'id_instansi' => 15
            ),
            51 => array (
                'id' => 52, 
                'id_keluaran' => 52, 
                'indikator_keluaran' => 'Jumlah pekebun yang difasilitasi',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 4,
                'id_program' => 22,
                'id_kegiatan' => 8,
                'id_subkegiatan' => 50,
                'id_instansi' => 13
            ),
            52 => array (
                'id' => 53, 
                'id_keluaran' => 53, 
                'indikator_keluaran' => 'Jumlah pelaku usaha yang dibina',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 4,
                'id_program' => 20,
                'id_kegiatan' => 26,
                'id_subkegiatan' => 45,
                'id_instansi' => 10
            ),
            53 => array (
                'id' => 54, 
                'id_keluaran' => 54, 
                'indikator_keluaran' => 'Luas kelapa sawit di kawasan hutan',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 4,
                'id_program' => 22,
                'id_kegiatan' => 27,
                'id_subkegiatan' => 49,
                'id_instansi' => 13
            ),
            54 => array (
                'id' => 55, 
                'id_keluaran' => 55, 
                'indikator_keluaran' => 'Persentase penyelesaian permasalahan hubungan industrial',
                'target' => 60,
                'satuan' => 'persen',
                'id_komponen' => 4,
                'id_program' => 25,
                'id_kegiatan' => 19,
                'id_subkegiatan' => 53,
                'id_instansi' => 4
            ),
            55 => array (
                'id' => 56, 
                'id_keluaran' => 56, 
                'indikator_keluaran' => 'Persentase perusahaan yang menerapak tata kelola kerja yang layak',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 4,
                'id_program' => 25,
                'id_kegiatan' => 31,
                'id_subkegiatan' => 52,
                'id_instansi' => 4
            ),
            56 => array (
                'id' => 57, 
                'id_keluaran' => 57, 
                'indikator_keluaran' => 'Jumlah kegiatan pengembangan kapasitas',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 5,
                'id_program' => 27,
                'id_kegiatan' => 7,
                'id_subkegiatan' => 55,
                'id_instansi' => 10
            ),
            57 => array (
                'id' => 58, 
                'id_keluaran' => 58, 
                'indikator_keluaran' => 'Jumlah kegiatan peningkatan kapasitas lembaga penyuluhan',
                'target' => 36,
                'satuan' => 'pertemuan',
                'id_komponen' => 5,
                'id_program' => 27,
                'id_kegiatan' => 7,
                'id_subkegiatan' => 58,
                'id_instansi' => 10
            ),
            58 => array (
                'id' => 59, 
                'id_keluaran' => 59, 
                'indikator_keluaran' => 'Jumlah lembaga pekebun yang tersertifikasi ISPO',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 5,
                'id_program' => 27,
                'id_kegiatan' => 36,
                'id_subkegiatan' => 57,
                'id_instansi' => 10
            ),
            59 => array (
                'id' => 60, 
                'id_keluaran' => 60, 
                'indikator_keluaran' => 'Jumlah pekebun yang menerima sosialisasi ISPO',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 5,
                'id_program' => 26,
                'id_kegiatan' => 7,
                'id_subkegiatan' => 54,
                'id_instansi' => 10
            ),
            60 => array (
                'id' => 61, 
                'id_keluaran' => 61, 
                'indikator_keluaran' => 'Jumlah Pelaku Usaha Kelapa Sawit Rakyat yang Difasilitasi dalam Pameran Dagang',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 5,
                'id_program' => 29,
                'id_kegiatan' => 34,
                'id_subkegiatan' => 59,
                'id_instansi' => 9
            ),
            61 => array (
                'id' => 62, 
                'id_keluaran' => 62, 
                'indikator_keluaran' => 'Jumlah STD-B yang diterbitkan Dinas kabupaten yang dalam pemenuhan persyaratan ISPO',
                'target' => 100,
                'satuan' => 'perlu diisi',
                'id_komponen' => 5,
                'id_program' => 27,
                'id_kegiatan' => 23,
                'id_subkegiatan' => 56,
                'id_instansi' => 10
            )
        ));
    }
}
